[build]
  command = "npm run start:prod"
  publish = "dist/conversion"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=0, must-revalidate"